name: example
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  self_animated_list:
    path: ../
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  collection: ^1.16.0
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
