name: example
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animated_list_view:
    path: ../
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  collection: ^1.16.0
  cupertino_icons: ^0.1.2

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
