name: animated_list_view
description: Simple widget lists with animation when children list is changed
version: 0.2.0
repository: https://github.com/sla-000/animated_list_view

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
