name: self_animated_list
description: AnimatedList which animates itself automatically when list of the items changed
version: 0.9.0
repository: https://github.com/sla-000/self_animated_list

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
