name: self_animated_list
description: AnimatedList which animates self when list of the items changed
version: 0.2.0
repository: https://github.com/sla-000/self_animated_list

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
