name: animated_list_view
description: Simple animated lists with reaction to children parameter changes
version: 0.2.0
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
