name: self_animated_list
description: AnimatedList with animation when list of the items changed
version: 0.2.0
repository: https://github.com/sla-000/animated_list_view

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
